<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BooksTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('books')->insert([
            [
            'id' => 1,
            'category_id' => 1,
            'title' => '100 MASALAH PEMBELAJARAN : Identifikasi dan Solusi Masalah Teknis Pengelolaan Pembelajaran di Kelas',
            'slug' => '100-masalah-pembelajaran',
            'author' => 'Lubis Grafura, M.Pd & Ari Wijayanti, S.Pd.',
            'publisher' => 'Ar-Ruzz Media',
            'published_year' => 2020,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 2,
            'category_id' => 2,
            'title' => '100+1 Cara Bahagia: 100 Inspirasi, 1 Aksi',
            'slug' => '100-1-cara-bahagia',
            'author' => 'Ainun Mahya & Triyanto',
            'publisher' => 'Trans Idea Publishing',
            'published_year' => 2020,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 3,
            'category_id' => 1,
            'title' => '101 JURUS JITU MENJADI GURU HEBAT',
            'slug' => '101-jurus-jitu-menjadi-guru-hebat',
            'author' => 'Haryono',
            'publisher' => 'Ar-Ruzz Media',
            'published_year' => 2020,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 4,
            'category_id' => 3,
            'title' => '101 RESEP KUE KERING KLASIK & MODERN',
            'slug' => '101-resep-kue-kering-klasik-modern',
            'author' => 'Ny. Rita TN',
            'publisher' => 'Kata Hati',
            'published_year' => 2020,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 5,
            'category_id' => 2,
            'title' => '18 Profesi Asyik Zaman Now',
            'slug' => '18-profesi-asyik-zaman-now',
            'author' => 'Keen Achroni',
            'publisher' => 'Trans Idea Publishing',
            'published_year' => 2019,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 6,
            'category_id' => 1,
            'title' => '19 KIAT SUKSES MEMBANGKITKAN MotivasiBELAJAR PESERTA DIDIK',
            'slug' => '19-kiat-sukses-membangkitkan-motivasi-belajar-peserta-didik',
            'author' => 'Erwin Widianworo S.Pd.',
            'publisher' => 'Ar-Ruzz Media',
            'published_year' => 2020,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 7,
            'category_id' => 1,
            'title' => '45 MODEL PEMBELAJARAN SPEKTAKULER',
            'slug' => '45-model-pembelajaran-spektakuler',
            'author' => 'Jasa Ungguh Muliawan',
            'publisher' => 'Ar-Ruzz Media',
            'published_year' => 2020,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 8,
            'category_id' => 4,
            'title' => '50 Dongeng Terpopuler Dunia: Fabel, Legenda, dan Kisah-kisah Lainnya',
            'slug' => '50-dongeng-terpopuler-dunia',
            'author' => 'Siti Masruroh',
            'publisher' => 'Trans Idea Publishing',
            'published_year' => 2018,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 9,
            'category_id' => 2,
            'title' => '50 Perkara tentang Jodoh',
            'slug' => '50-perkara-tentang-jodoh',
            'author' => 'Dwi Suwiknyo',
            'publisher' => 'Trans Idea Publishing',
            'published_year' => 2020,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 10,
            'category_id' => 5,
            'title' => '68 BUAH AJAIB PENANGKAL PENYAKIT',
            'slug' => '68-buah-ajaib-penangkal-penyakit',
            'author' => 'Wikanda Satria Putra',
            'publisher' => 'Kata Hati',
            'published_year' => 2020,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 11,
            'category_id' => 1,
            'title' => '68 MODEL PEMBELAJARAN INOVATIF DALAM KURIKULUM 2013',
            'slug' => '68-model-pembelajaran-inovatif-dalam-kurikulum-2013',
            'author' => 'Aris Shoimin',
            'publisher' => 'Ar-Ruzz Media',
            'published_year' => 2020,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 12,
            'category_id' => 1,
            'title' => '71 RAHASIA SUKSES MENJADI GURU: Plus Ide-ide Kreatif Untuk Anak',
            'slug' => '71-rahasia-sukses-menjadi-guru',
            'author' => 'Fatiharifah & Nisa Yustisia',
            'publisher' => 'Ar-Ruzz Media',
            'published_year' => 2020,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 13,
            'category_id' => 6,
            'title' => '75 RAHASIA ANAK CERDAS: Mengenali Potensi dan Strategi Mengembangkan Kecerdasan Buah Hati',
            'slug' => '75-rahasia-anak-cerdas',
            'author' => 'N. Yustisia',
            'publisher' => 'Kata Hati',
            'published_year' => 2020,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 14,
            'category_id' => 5,
            'title' => '78 Resep Antikanker, Diabetes, Kolesterol, Asam Urat',
            'slug' => '78-resep-antikanker-diabetes-kolesterol-asam-urat',
            'author' => 'Dewi Kurniasari',
            'publisher' => 'Trans Idea Publishing',
            'published_year' => 2018,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 15,
            'category_id' => 7,
            'title' => '99 PERMAINAN EDUKATIF UNTUK MELATIH KECERDASAN & KREATIVITAS ANAK',
            'slug' => '99-permainan-edukatif',
            'author' => 'Wikanda Satria Putra',
            'publisher' => 'Penunjang Pelajaran',
            'published_year' => 2020,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 16,
            'category_id' => 8,
            'title' => '9 JURUS CERDAS MENYONGSONG KARIER GEMILANG',
            'slug' => '9-jurus-cerdas-menyongsong-karier-gemilang',
            'author' => 'H. Heri Kuswara, S.Kom, M.Kom.',
            'publisher' => 'Ar-Ruzz Media',
            'published_year' => 2020,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 17,
            'category_id' => 2,
            'title' => '9 Smart Strategies to Be A Young Entrepreneur: Langkah Jitu Menjadi Pengusaha Sukses di Usia Muda',
            'slug' => '9-smart-strategies-to-be-a-young-entrepreneur',
            'author' => '',
            'publisher' => 'ar-Ruzz Media',
            'published_year' => 2020,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 18,
            'category_id' => 9,
            'title' => 'Akuaponik: Bisnis Unik Peluang Menarik',
            'slug' => 'akuaponik-bisnis-unik-peluang-menarik',
            'author' => 'Aditya Prananta',
            'publisher' => 'Trans Idea Publishing',
            'published_year' => 2018,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 19,
            'category_id' => 10,
            'title' => 'Ampuhnya Enzim Tubuh',
            'slug' => 'ampuhnya-enzim-tubuh',
            'author' => 'Eka Sumaryati dan Karina Tyas Widyaningrum',
            'publisher' => 'Trans Idea Publishing',
            'published_year' => 2020,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 20,
            'category_id' => 11,
            'title' => 'Aneka Kerajinan Kain Perca',
            'slug' => 'aneka-kerajinan-kain-perca',
            'author' => 'Puput Lestari',
            'publisher' => 'Litera Media Creativa',
            'published_year' => 2020,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 21,
            'category_id' => 11,
            'title' => 'Aneka Kreasi Aksesoris dari barang bekas (sedotan dan botol plastik)',
            'slug' => 'aneka-kreasi-aksesoris-dari-barang-bekas',
            'author' => 'Musiatun Wahaningsih',
            'publisher' => 'Litera Media Creativa',
            'published_year' => 2020,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 22,
            'category_id' => 11,
            'title' => 'Aneka Kreasi Gift Box',
            'slug' => 'aneka-kreasi-gift-box',
            'author' => 'Fatiah Arinda',
            'publisher' => 'Litera Media Creativa',
            'published_year' => 2020,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 23,
            'category_id' => 4,
            'title' => 'Apa yang Terjadi di Abad 20?: Kecil-kecil Hafal Peristiwa Sejarah Dunia',
            'slug' => 'apa-yang-terjadi-di-abad-20',
            'author' => 'Husna Widiani',
            'publisher' => 'Trans Idea Publishing',
            'published_year' => 2018,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 24,
            'category_id' => 1,
            'title' => 'ANALISIS & STRATEGI MENINGKATKAN DAYA SAING SEKOLAH',
            'slug' => 'analisis-strategi-meningkatkan-daya-saing-sekolah',
            'author' => 'Mohammad Saroni',
            'publisher' => 'Ar-Ruzz Media',
            'published_year' => 2020,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 25,
            'category_id' => 12,
            'title' => 'B.J. HABIBIE: Guru Terbesar Saya Adalah Otak Saya',
            'slug' => 'bj-habibie-guru-terbesar-saya-adalah-otak-saya',
            'author' => 'Ade Ma\'ruf',
            'publisher' => 'Ar-Ruzz Media',
            'published_year' => 2020,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
                'id' => 26,
                'category_id' => 13,
                'title' => 'Belajar & cerdas bersama psikolog dunia: kritik terhadap dunia pendidikan, pembelajaran, dan kecerdasan',
                'slug' => 'belajar-cerdas-bersama-psikolog-dunia',
                'author' => 'C. George Boeree ; penerjemah, Abdul Qodir Shaleh',
                'publisher' => 'Psikologi',
                'published_year' => 2020,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 27,
                'category_id' => 39,
                'title' => 'Belajar Teknik Merangkai Janur untuk Dekorasi',
                'slug' => 'belajar-teknik-merangkai-janur',
                'author' => 'Cikal Gading',
                'publisher' => 'Lembaga Kajian Profesi',
                'published_year' => 2018,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 28,
                'category_id' => 9,
                'title' => 'Berkenalan dengan Teknik Vertikultur: Tata Cara dan Keunggulannya',
                'slug' => 'berkenalan-dengan-teknik-vertikultur',
                'author' => 'Kurniawan Dwi Setyadi',
                'publisher' => 'Trans Idea Publishing',
                'published_year' => 2018,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 29,
                'category_id' => 5,
                'title' => 'BERDAMAI DENGAN ALZHEIMER: Strategi Menjadi Caregiver bagi Penderita Penyakit Alzheimer',
                'slug' => 'berdamai-dengan-alzheimer',
                'author' => 'Rose Kusuma',
                'publisher' => 'Kata Hati',
                'published_year' => 2020,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 30,
                'category_id' => 17,
                'title' => 'BERIBADAH TANPA HENTI: Panduan Beribadah Bagi Wanita Haid',
                'slug' => 'beribadah-tanpa-henti',
                'author' => 'Irham Sya\'roni & Sawaun Amin',
                'publisher' => 'Kata Hati',
                'published_year' => 2020,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 31,
                'category_id' => 1,
                'title' => 'BEST PRACTICE: Langkah Efektif Meningkatkan Kualitas Karakter Warga Sekolah',
                'slug' => 'best-practice',
                'author' => 'Mohammad Saroni',
                'publisher' => 'Ar-Ruzz Media',
                'published_year' => 2020,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 32,
                'category_id' => 12,
                'title' => 'Bill Gates: Cara Kaya Ala Pendiri Microsoft',
                'slug' => 'bill-gates-cara-kaya',
                'author' => 'Dayu Pratyahara',
                'publisher' => 'Buku Bijak',
                'published_year' => 2022,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 33,
                'category_id' => 14,
                'title' => 'Bisnis Modal 10 Jutaan: Inspirasi Bisnis dengan Modal Minimal Untung Maksimal',
                'slug' => 'bisnis-modal-10-jutaan',
                'author' => 'Oppi Andini',
                'publisher' => 'Garasi',
                'published_year' => 2020,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 34,
                'category_id' => 15,
                'title' => 'Budidaya Ayam Potong: Peluang Usaha Unggulan',
                'slug' => 'budidaya-ayam-potong',
                'author' => 'Saelindra',
                'publisher' => 'Litera Media Creativa',
                'published_year' => 2020,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 35,
                'category_id' => 1,
                'title' => 'BRANDED SCHOOL: Membangun Sekolah Unggul Berbasis Peningkatan Mutu',
                'slug' => 'branded-school',
                'author' => 'Barnawi & Mohammad Arifin',
                'publisher' => 'Ar-Ruzz Media',
                'published_year' => 2020,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 36,
                'category_id' => 1,
                'title' => 'BUKU PANDUAN GURU HEBAT INDONESIA: Rahasia Menjadi Guru Hebat dengan Keahlian Public Speaking, Menulis Buku & Artikel di Media Massa',
                'slug' => 'buku-panduan-guru-hebat-indonesia',
                'author' => 'Dr. Aminulloh Syarbini, M.Ag.',
                'publisher' => 'Ar-Ruzz Media',
                'published_year' => 2020,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 37,
                'category_id' => 16,
                'title' => 'Buku Panduan Operator Komputer',
                'slug' => 'buku-panduan-operator-komputer',
                'author' => 'Litharia Mandavena Sari',
                'publisher' => 'Lembaga Kajian Profesi',
                'published_year' => 2018,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 38,
                'category_id' => 17,
                'title' => 'BUKU PINTAR HAJI DAN UMRAH',
                'slug' => 'buku-pintar-haji-dan-umrah',
                'author' => 'K.H. Imam Jazuli, M.A.',
                'publisher' => 'Ar-Ruzz Media',
                'published_year' => 2020,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 39,
                'category_id' => 5,
                'title' => 'Buku Pintar Olahraga Sehat: Penyakit Bablas dengan Olahraga yang Pas',
                'slug' => 'buku-pintar-olahraga-sehat',
                'author' => 'Prof. Dr. dr. Anies, M.Kes, PKK',
                'publisher' => 'Buku Bijak',
                'published_year' => 2022,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 40,
                'category_id' => 1,
                'title' => 'BUNG HATTA & PENDIDIKAN KARAKTER',
                'slug' => 'bung-hatta-pendidikan-karakter',
                'author' => 'Dr. Silfia Hanani, M.Si., Susi Ratna Sari, M.Pd',
                'publisher' => 'Ar-Ruzz Media',
                'published_year' => 2018,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 41,
                'category_id' => 18,
                'title' => 'CAHAYAMU TAK BISA KUTAWAR: Novel Biografi Mahfud MD',
                'slug' => 'cahayamu-tak-bisa-kutawar',
                'author' => 'Aguk Irawan MN',
                'publisher' => 'Ar-Ruzz Media',
                'published_year' => 2020,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 42,
                'category_id' => 5,
                'title' => 'CANTIK DAN SEHAT DENGAN HERBAL: Aneka Racikan & Ramuan Rahasia Khusus Wanita',
                'slug' => 'cantik-dan-sehat-dengan-herbal',
                'author' => 'Mudha Al-Lubna',
                'publisher' => 'Kata Hati',
                'published_year' => 2020,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 43,
                'category_id' => 19,
                'title' => 'Cantik Luar Dalam ala Muslimah',
                'slug' => 'cantik-luar-dalam-ala-muslimah',
                'author' => 'Qari\'ah Hamid, S.S',
                'publisher' => 'Trans Idea Publishing',
                'published_year' => 2020,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 44,
                'category_id' => 1,
                'title' => 'CARA CEPAT BELAJAR BACA TULIS AL-QURAN UNTUK SMA-MA',
                'slug' => 'cara-cepat-belajar-baca-tulis-al-quran',
                'author' => 'Abu Firly Bassam Taqiy',
                'publisher' => 'Ar-Ruzz Media',
                'published_year' => 2020,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 45,
                'category_id' => 9,
                'title' => 'Cara Cerdas Budidaya Jahe: Panen Maksimal',
                'slug' => 'cara-cerdas-budidaya-jahe',
                'author' => 'Keen Achroni',
                'publisher' => 'Trans Idea Publishing',
                'published_year' => 2018,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 46,
                'category_id' => 6,
                'title' => 'CARA CERDAS MELEJITKAN IQ KREATIF ANAK',
                'slug' => 'cara-cerdas-melejitkan-iq-kreatif-anak',
                'author' => 'Tuhana Taufiq Andrianto',
                'publisher' => 'Kata Hati',
                'published_year' => 2020,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 47,
                'category_id' => 1,
                'title' => 'CHARACTER BUILDING : Optimalisasi Peran Pendidikan dalam Pengembangan Ilmu & Pembentukan Karakter Bangsa',
                'slug' => 'character-building',
                'author' => 'Ngainun Naim',
                'publisher' => 'Ar-Ruzz Media',
                'published_year' => 2020,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 48,
                'category_id' => 2,
                'title' => 'Couple Book for Husband and Wife: Membangun Surga dalam Rumah Tangga',
                'slug' => 'couple-book-for-husband-and-wife',
                'author' => 'Luluk Bambang Sulistyo & Nur Iswanti Hasani',
                'publisher' => 'Trans Idea Publishing',
                'published_year' => 2018,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 49,
                'category_id' => 12,
                'title' => 'Cut Nyak Dien: Pejuang Wanita yang Tak Kenal Menyerah',
                'slug' => 'cut-nyak-dien',
                'author' => 'Arslan Mukhtar',
                'publisher' => 'Edulitera',
                'published_year' => 2022,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 50,
                'category_id' => 5,
                'title' => 'DAUN DAHSYAT: Pencegah & Penyembuh Penyakit',
                'slug' => 'daun-dahsyat',
                'author' => 'Tim Afin and Friends',
                'publisher' => 'Kata Hati',
                'published_year' => 2020,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
            'id' => 51,
            'category_id' => 1,
            'title' => 'DESAIN PEMBELAJARAN BERBASIS PENDIDIKAN KARAKTER',
            'slug' => 'desain-pembelajaran-berbasis-pendidikan-karakter',
            'author' => 'Asmaun Sahlan & Angga Teguh Prastyo',
            'publisher' => 'Ar-Ruzz Media',
            'published_year' => 2020,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 52,
            'category_id' => 1,
            'title' => 'DESAIN PEMBELAJARAN PENDIDIKAN: Tata Rancang Pembelajaran Menuju Pencapaian Kompetensi',
            'slug' => 'desain-pembelajaran-pendidikan',
            'author' => 'Novan Ardi Wiyani, M.Pd.I',
            'publisher' => 'Ar-Ruzz Media',
            'published_year' => 2020,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 53,
            'category_id' => 39,
            'title' => 'DIY Life Hacks: 99 Cara Bikin Hidup Lebih Mudah',
            'slug' => 'diy-life-hacks',
            'author' => 'Darma Dwinov',
            'publisher' => 'Trans Idea Publishing',
            'published_year' => 2018,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 54,
            'category_id' => 20,
            'title' => 'Don\'t Say "Go" but Say "Let\'s Go" Apa-apa Saja yang Harus dilakukan Manajer dan Supervisor',
            'slug' => 'dont-say-go-but-say-lets-go',
            'author' => 'Keen Achroni',
            'publisher' => 'Trans Idea Publishing',
            'published_year' => 2020,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 55,
            'category_id' => 4,
            'title' => 'Ekspres Belajar Bahasa Arab',
            'slug' => 'ekspres-belajar-bahasa-arab',
            'author' => 'Sigit Murdiantoro, S. Pd',
            'publisher' => 'Trans Idea Publishing',
            'published_year' => 2020,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 56,
            'category_id' => 21,
            'title' => 'Enjoying Life with Hypnosis',
            'slug' => 'enjoying-life-with-hypnosis',
            'author' => 'Eiroul BM',
            'publisher' => 'Trans Idea Publishing',
            'published_year' => 2020,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 57,
            'category_id' => 22,
            'title' => 'From Fangirling to Something: Mengubah Hobi Menjadi Prestasi',
            'slug' => 'from-fangirling-to-something',
            'author' => 'Tristanti Wahyuni',
            'publisher' => 'Ar-Ruzz Media',
            'published_year' => 2022,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 58,
            'category_id' => 1,
            'title' => 'FULL DAY SCHOOL: Konsep, Manajemen, & Quality Control',
            'slug' => 'full-day-school',
            'author' => 'Jamal Ma’mur Asmani',
            'publisher' => 'Ar-Ruzz Media',
            'published_year' => 2020,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 59,
            'category_id' => 2,
            'title' => 'Gagal Bukan Berarti Sia-Sia',
            'slug' => 'gagal-bukan-berarti-sia-sia',
            'author' => 'Teo Sutan',
            'publisher' => 'Trans Idea Publishing',
            'published_year' => 2020,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 60,
            'category_id' => 10,
            'title' => 'Girl\'s Guide for Health and Beauty',
            'slug' => 'girls-guide-for-health-and-beauty',
            'author' => 'Karina Tyas',
            'publisher' => 'Trans Idea Publishing',
            'published_year' => 2020,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 61,
            'category_id' => 1,
            'title' => 'GURU GOKIL ZAMAN NOW: Cara Unik Menemukan Kreativitas Tanpa batas',
            'slug' => 'guru-gokil-zaman-now',
            'author' => 'Asrul Right',
            'publisher' => 'Ar-Ruzz Media',
            'published_year' => 2018,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 62,
            'category_id' => 1,
            'title' => 'GURU PROFESIONAL: Pedoman Kerja, Kualifikasi, & Kompetensi Guru',
            'slug' => 'guru-profesional',
            'author' => 'Jamil Suprihatiningrum, M.Pd.Si',
            'publisher' => 'Ar-Ruzz Media',
            'published_year' => 2020,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
                'id' => 63,
                'category_id' => 12,
                'title' => 'Cut Nyak Meutia: Pejuang Aceh yang Jelita dan Pemberani',
                'slug' => 'cut-nyak-meutia',
                'author' => 'Ananda Mona',
                'publisher' => 'Edulitera',
                'published_year' => 2022,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 64,
                'category_id' => 38,
                'title' => 'Hafalan Otodidak Percakapan Harian Bahasa Mandarin',
                'slug' => 'hafalan-otodidak-percakapan-harian-bahasa-mandarin',
                'author' => 'Thia R',
                'publisher' => 'Trans Idea Publishing',
                'published_year' => 2020,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 65,
                'category_id' => 39,
                'title' => 'Handmade Bantal Unik dan Lucu dengan Bahan-Bahan Sederhana',
                'slug' => 'handmade-bantal-unik-dan-lucu',
                'author' => 'Muharini M.',
                'publisher' => 'Lembaga Kajian Profesi',
                'published_year' => 2018,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 66,
                'category_id' => 23,
                'title' => 'Hijab Style For Teens: Dari Sekolah, Gaul, hingga Pesta',
                'slug' => 'hijab-style-for-teens',
                'author' => 'Afin Murtie, Sanggar Rias Arsita',
                'publisher' => 'Trans Idea Publishing',
                'published_year' => 2020,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 67,
                'category_id' => 2,
                'title' => 'Hipnosis: Seni Mengendalikan Pikiran',
                'slug' => 'hipnosis-seni-mengendalikan-pikiran',
                'author' => 'Eiroul BM',
                'publisher' => 'Trans Idea Publishing',
                'published_year' => 2018,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 68,
                'category_id' => 1,
                'title' => 'HYPNOTEACHING: Revolusi Gaya Mengajar untuk Melejitkan Prestasi Siswa',
                'slug' => 'hypnoteaching-revolusi-gaya-mengajar',
                'author' => 'Ali Akbar Navis, Spd. CHt, Cl.',
                'publisher' => 'Ar-Ruzz Media',
                'published_year' => 2020,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 69,
                'category_id' => 1,
                'title' => 'HYPNOTEACHING: Seni Ajar Mengeksplorasi Otak Peserta Didik',
                'slug' => 'hypnoteaching-seni-ajar-mengeksplorasi-otak',
                'author' => 'N. Yustisia',
                'publisher' => 'Ar-Ruzz Media',
                'published_year' => 2020,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 70,
                'category_id' => 1,
                'title' => 'GAGALNYA PENDIDIKAN KARAKTER: Analisis dan Solusi Pengendalian Karakter Emas Anak Didik',
                'slug' => 'gagalnya-pendidikan-karakter',
                'author' => 'Mohammad Takdir Ilahi',
                'publisher' => 'Ar-Ruzz Media',
                'published_year' => 2020,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 71,
                'category_id' => 15,
                'title' => 'Jurus Sakti Bertaman Tomat di Lahan Sempit',
                'slug' => 'jurus-sakti-bertaman-tomat',
                'author' => 'Alviani Putri',
                'publisher' => 'Litera Media Creativa',
                'published_year' => 2020,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 72,
                'category_id' => 5,
                'title' => 'JUS AMPUH BUAH & SAYUR BASMI BERBAGAI PENYAKIT',
                'slug' => 'jus-ampuh-buah-sayur',
                'author' => 'Afin Murtie',
                'publisher' => 'Kata Hati',
                'published_year' => 2020,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 73,
                'category_id' => 16,
                'title' => 'Kamus Saku Bahasa Jepang untuk Dunia Kerja',
                'slug' => 'kamus-saku-bahasa-jepang',
                'author' => 'Toniko Zahira',
                'publisher' => 'Lembaga Kajian Profesi',
                'published_year' => 2018,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 74,
                'category_id' => 4,
                'title' => 'Kecil-kecil Jago Eksperimen Sains',
                'slug' => 'kecil-kecil-jago-eksperimen-sains',
                'author' => 'Nini Subini, S. Pd',
                'publisher' => 'Trans Idea Publishing',
                'published_year' => 2020,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 75,
                'category_id' => 21,
                'title' => 'Kenalan dengan Diri Sendiri: 45 cara Membaca Kepribadian',
                'slug' => 'kenalan-dengan-diri-sendiri',
                'author' => 'Ade Rakhma Novita Sari dan Ayu Larasati',
                'publisher' => 'Trans Idea Publishing',
                'published_year' => 2020,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 76,
                'category_id' => 39,
                'title' => 'Kerajinan Bunga Kering: Inspirasi Baru Bisnis Rumahan',
                'slug' => 'kerajinan-bunga-kering',
                'author' => 'Liliana Dewantari',
                'publisher' => 'Lembaga Kajian Profesi',
                'published_year' => 2018,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 77,
                'category_id' => 6,
                'title' => 'KESALAHAN-KESALAHAN FATAL (YANG HARUS DIHINDARI) ORANGTUA DALAM MERAWAT & MENDIDIK BUAH HATI',
                'slug' => 'kesalahan-fatal-orangtua',
                'author' => 'Anisa\'ul Jannah, Wikanda Satria Putra',
                'publisher' => 'Kata Hati',
                'published_year' => 2020,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 78,
                'category_id' => 39,
                'title' => 'Keterampilan dari Bubur Kertas: Ide Unik Usaha Kreatif',
                'slug' => 'keterampilan-dari-bubur-kertas',
                'author' => 'Ninggar Saputri',
                'publisher' => 'Lembaga Kajian Profesi',
                'published_year' => 2018,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 79,
                'category_id' => 12,
                'title' => 'KH. AHMAD DAHLAN : Biografi Singkat (1869-1923)',
                'slug' => 'kh-ahmad-dahlan',
                'author' => 'Adi Nugraha',
                'publisher' => 'Garasi',
                'published_year' => 2020,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 80,
                'category_id' => 12,
                'title' => 'KH. HASYIM ASY\'ARI ; Biografi Singkat 1871-1947',
                'slug' => 'kh-hasyim-asyari',
                'author' => 'Muhamad Rifai',
                'publisher' => 'Garasi',
                'published_year' => 2020,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 81,
                'category_id' => 12,
                'title' => 'KI HAJAR DEWANTARA; Biografi Singkat 1989-1959',
                'slug' => 'ki-hajar-dewantara',
                'author' => 'Suparto Raharjo',
                'publisher' => 'Garasi',
                'published_year' => 2020,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 82,
                'category_id' => 12,
                'title' => 'K.H. Abdullah Zain Salam: Biografi Singkat',
                'slug' => 'kh-abdullah-zain-salam',
                'author' => 'Adrian Mahira',
                'publisher' => 'Garasi',
                'published_year' => 2022,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 83,
                'category_id' => 15,
                'title' => 'Kiat Sukses Beternak Burung Puyuh',
                'slug' => 'kiat-sukses-beternak-burung-puyuh',
                'author' => 'Ulin Nuha',
                'publisher' => 'Litera Media Creativa',
                'published_year' => 2020,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 84,
                'category_id' => 9,
                'title' => 'Kiat Sukses Budidaya Kepiting Hasil Optimal',
                'slug' => 'kiat-sukses-budidaya-kepiting',
                'author' => 'Oppi Kristanti',
                'publisher' => 'Lembaga Kajian Profesi',
                'published_year' => 2018,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 85,
                'category_id' => 1,
                'title' => 'KEPEMIMPINAN VISIONER KEPALA SEKOLAH DALAM MENINGKATKAN MUTU PENDIDIKAN',
                'slug' => 'kepemimpinan-visioner-kepala-sekolah',
                'author' => 'Dr. Nurul Hidayah, M.Ag.',
                'publisher' => 'Ar-Ruzz Media',
                'published_year' => 2020,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
            'id' => 86,
            'category_id' => 28,
            'title' => 'Kompeten KSN Ekonomi SMA/MA',
            'slug' => 'kompeten-ksn-ekonomi-sma-ma',
            'author' => 'Nur Hidayah, S.Pd.',
            'publisher' => 'Pixelindo',
            'published_year' => 2022,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 87,
            'category_id' => 28,
            'title' => 'Kompeten KSN Fisika SMA/MA',
            'slug' => 'kompeten-ksn-fisika-sma-ma',
            'author' => 'Yani Oktavia, S.Pd.',
            'publisher' => 'Pixelindo',
            'published_year' => 2022,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 88,
            'category_id' => 28,
            'title' => 'Kompeten KSN Geografi SMA/MA',
            'slug' => 'kompeten-ksn-geografi-sma-ma',
            'author' => 'Gita Arfiani',
            'publisher' => 'Pixelindo',
            'published_year' => 2022,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 89,
            'category_id' => 28,
            'title' => 'Kompeten KSN Kimia SMA/MA',
            'slug' => 'kompeten-ksn-kimia-sma-ma',
            'author' => 'Ibnu Shohib, S,Pd.Si',
            'publisher' => 'Pixelindo',
            'published_year' => 2022,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 90,
            'category_id' => 28,
            'title' => 'Kompeten KSN Matematika SMA/MA',
            'slug' => 'kompeten-ksn-matematika-sma-ma',
            'author' => 'Tim Pembina Prestasi',
            'publisher' => 'Pixelindo',
            'published_year' => 2022,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 91,
            'category_id' => 25,
            'title' => 'KOMUNIKASI ANTARPRIBADI: Teori & Praktik',
            'slug' => 'komunikasi-antarpribadi-teori-praktik',
            'author' => 'Dr. Silfia Hanani, M.Si.',
            'publisher' => 'Ar-Ruzz Media',
            'published_year' => 2020,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 92,
            'category_id' => 24,
            'title' => 'Komunikasi Dibalik Busana',
            'slug' => 'komunikasi-dibalik-busana',
            'author' => 'Sihabuddin, S.I.Kom., M.I.Kom.',
            'publisher' => 'Ar-Ruzz Media',
            'published_year' => 2020,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 93,
            'category_id' => 11,
            'title' => 'Kreasi Cantik dari bahan Pita',
            'slug' => 'kreasi-cantik-dari-bahan-pita',
            'author' => 'Teo Sutan',
            'publisher' => 'Litera Media Creativa',
            'published_year' => 2020,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 94,
            'category_id' => 11,
            'title' => 'Kreasi Tas dan Dompet dari Kain Kanvas dan Kain Katun',
            'slug' => 'kreasi-tas-dan-dompet-dari-kain-kanvas',
            'author' => 'Alvi Putri',
            'publisher' => 'Litera Media Creativa',
            'published_year' => 2020,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 95,
            'category_id' => 2,
            'title' => 'Kreatif adalah Koentji: Panduan Hidup Asyik Ala Manusia Kekinian',
            'slug' => 'kreatif-adalah-koentji',
            'author' => 'Keen Achroni',
            'publisher' => 'Trans Idea Publishing',
            'published_year' => 2018,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 96,
            'category_id' => 15,
            'title' => 'Kreatif Bertanam Semangka Nonbiji',
            'slug' => 'kreatif-bertanam-semangka-nonbiji',
            'author' => 'Tristanti Wahyuni',
            'publisher' => 'Litera Media Creativa',
            'published_year' => 2020,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 97,
            'category_id' => 10,
            'title' => 'Kunci Tepat Diet Sehat: Cara Langsing Nggak Pakai Pusing',
            'slug' => 'kunci-tepat-diet-sehat',
            'author' => 'Anna Nurlaila Kurniasari & Dian D.A',
            'publisher' => 'Trans Idea Publishing',
            'published_year' => 2020,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 98,
            'category_id' => 40,
            'title' => 'Kupas Tuntas Kimia SMA Kelas X,XI,XII',
            'slug' => 'kupas-tuntas-kimia-sma',
            'author' => 'Ibnu Shohib, S.Pd. Si',
            'publisher' => 'Trans Idea Publishing',
            'published_year' => 2020,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 99,
            'category_id' => 39,
            'title' => 'Kreasi Lilin Aroma Terapi: Inspirasi Hobi dan Bisnis',
            'slug' => 'kreasi-lilin-aroma-terapi',
            'author' => 'Mirafa Anindya',
            'publisher' => 'Lembaga Kajian Profesi',
            'published_year' => 2018,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 100,
            'category_id' => 41,
            'title' => 'Lakon Asmaraloka',
            'slug' => 'lakon-asmaraloka',
            'author' => 'Mahadewa Adi Seta',
            'publisher' => 'Buku Bijak',
            'published_year' => 2020,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 101,
            'category_id' => 42,
            'title' => 'Layla Majnun',
            'slug' => 'layla-majnun',
            'author' => 'Syaikh Nizami',
            'publisher' => 'Buku Bijak',
            'published_year' => 2020,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 102,
            'category_id' => 27,
            'title' => 'Leave Your Boring Box: Kumpulan Kisah Sederhana yang Menjadi Mewah Karena Kalian Membacanya',
            'slug' => 'leave-your-boring-box',
            'author' => 'Emirfan',
            'publisher' => 'Buku Bijak',
            'published_year' => 2022,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 103,
            'category_id' => 1,
            'title' => 'MANAJEMEN & KEPEMIMPINAN KEPALA SEKOLAH: Konsep, Strategi, & Inovasi Menuju Sekolah efektif',
            'slug' => 'manajemen-kepemimpinan-kepala-sekolah',
            'author' => 'Andang, M.Pd.',
            'publisher' => 'Ar-Ruzz Media',
            'published_year' => 2020,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 104,
            'category_id' => 1,
            'title' => 'MANAJEMEN KELAS: Teori dan Aplikasi untuk Menciptakan Kelas yang Kondusif',
            'slug' => 'manajemen-kelas',
            'author' => 'Novan Ardi Wiyani',
            'publisher' => 'Ar-Ruzz Media',
            'published_year' => 2020,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 105,
            'category_id' => 26,
            'title' => 'MANAJEMEN PERPUSTAKAAN SEKOLAH',
            'slug' => 'manajemen-perpustakaan-sekolah',
            'author' => 'Drs. Hartono, SS, M.Hum',
            'publisher' => 'Ar-Ruzz Media',
            'published_year' => 2020,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 106,
            'category_id' => 1,
            'title' => 'MANAJEMEN SARANA & PRASARANA SEKOLAH',
            'slug' => 'manajemen-sarana-prasarana-sekolah',
            'author' => 'Barnawi & M. Arifin',
            'publisher' => 'Ar-Ruzz Media',
            'published_year' => 2020,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 107,
            'category_id' => 42,
            'title' => 'Mata Raisa',
            'slug' => 'mata-raisa',
            'author' => 'Abidah El Khalieqy',
            'publisher' => 'Buku Bijak',
            'published_year' => 2020,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 108,
            'category_id' => 1,
            'title' => 'MANAJEMEN PENDIDIKAN: Komponen-Komponen Elementer Kemajuan Sekolah',
            'slug' => 'manajemen-pendidikan',
            'author' => 'Kompri, M.Pd.I',
            'publisher' => 'Ar-Ruzz Media',
            'published_year' => 2020,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 109,
            'category_id' => 40,
            'title' => 'Matematrik: Top Rumus & Materi SMA IPS',
            'slug' => 'matematrik-top-rumus-materi-sma-ips',
            'author' => 'Rahmani Dwi Fajarsih, S. Si',
            'publisher' => 'Trans Idea Publishing',
            'published_year' => 2020,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 110,
            'category_id' => 30,
            'title' => 'MENGENAL SARAF PADA MANUSIA',
            'slug' => 'mengenal-saraf-pada-manusia',
            'author' => 'Ria Setyo Mardani',
            'publisher' => 'Trans Idea Publishing',
            'published_year' => 2020,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 111,
            'category_id' => 9,
            'title' => 'Mengintip Peluang Bisnis Budidaya Sayur Organik',
            'slug' => 'mengintip-peluang-bisnis-budidaya-sayur-organik',
            'author' => 'Keen Achroni',
            'publisher' => 'Trans Idea Publishing',
            'published_year' => 2018,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 112,
            'category_id' => 1,
            'title' => 'MENJADI ORANG TUA IDAMAN DENGAN HYPNOPARENTING',
            'slug' => 'menjadi-orang-tua-idaman-dengan-hypnoparenting',
            'author' => 'Ali Akbar Navis, Spd. CHt, Cl.',
            'publisher' => 'Kata Hati',
            'published_year' => 2020,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 113,
            'category_id' => 4,
            'title' => 'Metode Master Semua Materi & Rumus Matematika SMA X, XI, XII',
            'slug' => 'metode-master-semua-materi-rumus-matematika-sma',
            'author' => 'Isti Nurul Khotimah',
            'publisher' => 'Trans Idea Publishing',
            'published_year' => 2020,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 114,
            'category_id' => 2,
            'title' => 'Minimalisme: Seni Menyederhanakan Hidup',
            'slug' => 'minimalisme-seni-menyederhanakan-hidup',
            'author' => 'Diptra',
            'publisher' => 'Trans Idea Publishing',
            'published_year' => 2018,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 115,
            'category_id' => 1,
            'title' => 'MODEL-MODEL PEMBELAJARAN INOVATIF; Alternatif Desain Pembelajaran yang Menyenangkan',
            'slug' => 'model-model-pembelajaran-inovatif',
            'author' => 'Muhammad Fathurrohman, M.Pd.I',
            'publisher' => 'Ar-Ruzz Media',
            'published_year' => 2020,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 116,
            'category_id' => 12,
            'title' => 'MOHAMMAD HATTA : Biografi Singkat (1902-1980)',
            'slug' => 'mohammad-hatta-biografi-singkat',
            'author' => 'Salman Alfarizi',
            'publisher' => 'Garasi',
            'published_year' => 2020,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 117,
            'category_id' => 2,
            'title' => 'Muda Kaya Mendunia',
            'slug' => 'muda-kaya-mendunia',
            'author' => 'AT. Erik Triadi & Nor Islafatun',
            'publisher' => 'Trans Idea Publishing',
            'published_year' => 2020,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 118,
            'category_id' => 2,
            'title' => 'Muslimah Kudu Happy',
            'slug' => 'muslimah-kudu-happy',
            'author' => 'Dian Nafi',
            'publisher' => 'Trans Idea Publishing',
            'published_year' => 2020,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 119,
            'category_id' => 15,
            'title' => 'Ngulik Resep Rahasia Budidaya Ikan Nila',
            'slug' => 'ngulik-resep-rahasia-budidaya-ikan-nila',
            'author' => 'Muhammad Ulin Nuha, S.Pi & Indah Afiani',
            'publisher' => 'Litera Media Creativa',
            'published_year' => 2020,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 120,
            'category_id' => 5,
            'title' => 'PANDUAN PRAKTIS PERTOLONGAN PERTAMA PADA KEDARURATAN P3K',
            'slug' => 'panduan-praktis-pertolongan-pertama-pada-kedaruratan-p3k',
            'author' => 'dr. Niluh Swasanti & Wikanda Satria Putra',
            'publisher' => 'Kata Hati',
            'published_year' => 2020,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 121,
            'category_id' => 9,
            'title' => 'Panduan Tepat Cara Budidaya Kelapa Hibrida',
            'slug' => 'panduan-tepat-cara-budidaya-kelapa-hibrida',
            'author' => 'Haris Sucipto Hadi',
            'publisher' => 'Trans Idea Publishing',
            'published_year' => 2018,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 122,
            'category_id' => 15,
            'title' => 'Panen Laba dari Ladang Pepaya',
            'slug' => 'panen-laba-dari-ladang-pepaya',
            'author' => 'Eista Swaesti',
            'publisher' => 'Litera Media Creativa',
            'published_year' => 2020,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 123,
            'category_id' => 15,
            'title' => 'Panen Uang dari Kebun Pisang',
            'slug' => 'panen-uang-dari-kebun-pisang',
            'author' => 'Puput Alviani',
            'publisher' => 'Litera Media Creativa',
            'published_year' => 2020,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 124,
            'category_id' => 9,
            'title' => 'Pasti Kaya dengan Usaha Budidaya Lidah Buaya',
            'slug' => 'pasti-kaya-dengan-usaha-budidaya-lidah-buaya',
            'author' => 'Satisa Maryam',
            'publisher' => 'Lembaga Kajian Profesi',
            'published_year' => 2018,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 125,
            'category_id' => 1,
            'title' => 'MENJADI ORANG TUA IDAMAN DENGAN HYPNOPARENTING',
            'slug' => 'menjadi-orang-tua-idaman-dengan-hypnoparenting-2',
            'author' => 'Ali Akbar Navis, Spd. CHt, Cl.',
            'publisher' => 'Kata Hati',
            'published_year' => 2020,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
            'id' => 126,
            'category_id' => 1,
            'title' => 'PEACE EDUCATION : Kajian Sejarah, Konsep, & Relevansinya dengan Pendidikan Islam',
            'slug' => 'peace-education',
            'author' => 'M Nurul Ikhsan Saleh',
            'publisher' => 'Ar-Ruzz Media',
            'published_year' => 2020,
            'description' => null,
            'stock' => 10,
            'cover_image' => null
            ],
            [
                'id' => 127,
                'category_id' => 15,
                'title' => 'Pedoman Lengkap Budidaya Buah Naga Antigagal',
                'slug' => 'pedoman-lengkap-budidaya-buah-naga-antigagal',
                'author' => 'Tristanti Wahyuni',
                'publisher' => 'Litera Media Creativa',
                'published_year' => 2020,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 128,
                'category_id' => 1,
                'title' => 'PEMBELAJARAN INOVATIF: Strategi Mengelola Kelas Secara Efektif dan Menyenangkan',
                'slug' => 'pembelajaran-inovatif',
                'author' => 'Khanifatul, S.Pd.',
                'publisher' => 'Ar-Ruzz Media',
                'published_year' => 2020,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 129,
                'category_id' => 1,
                'title' => 'PENDIDIKAN AGAMA DALAM KELUARGA: Revitalisasi Peran Keluarga dalam Membangun Generasi Bangsa yang Berkarakter',
                'slug' => 'pendidikan-agama-dalam-keluarga',
                'author' => 'Dr.H.Moh Haitami Salim, M.Ag.',
                'publisher' => 'Ar-Ruzz Media',
                'published_year' => 2020,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 130,
                'category_id' => 1,
                'title' => 'PENDIDIKAN ANTIKORUPSI: Strategi Internalisasi Nilai-Nilai Islami dalam Menumbuhkan Kesadaran Antikorupsi di Sekolah',
                'slug' => 'pendidikan-antikorupsi',
                'author' => 'H. Muhamad Nurdin, S.Ag, M.Pd.I',
                'publisher' => 'Ar-Ruzz Media',
                'published_year' => 2019,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 131,
                'category_id' => 1,
                'title' => 'PENDIDIKAN INKLUSIF: Konsep & Aplikasi',
                'slug' => 'pendidikan-inklusif',
                'author' => 'Mohammad Takdir Ilahi',
                'publisher' => 'Ar-Ruzz Media',
                'published_year' => 2020,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 132,
                'category_id' => 1,
                'title' => 'PENDIDIKAN ISLAM BERBASIS PROBLEM SOSIAL',
                'slug' => 'pendidikan-islam-berbasis-problem-sosial',
                'author' => 'Prof. Dr. Sutrisno, M.Ag. & Muhyidin Albarobis, M.Pd.I',
                'publisher' => 'Ar-Ruzz Media',
                'published_year' => 2020,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 133,
                'category_id' => 1,
                'title' => 'Pendidikan Karakter Berbasis Total Quality Management (TQM): Konsep dan Aplikasi di Sekolah',
                'slug' => 'pendidikan-karakter-berbasis-tqm',
                'author' => 'Novan Ardy Wiyani',
                'publisher' => 'Ar-Ruzz Media',
                'published_year' => 2020,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 134,
                'category_id' => 1,
                'title' => 'PENDIDIKAN KARAKTER TANPA KEKERASAN Upaya Membentuk Karakter Bangsa yang Lebih Baik',
                'slug' => 'pendidikan-karakter-tanpa-kekerasan',
                'author' => 'Mohammad Saroni',
                'publisher' => 'Ar-Ruzz Media',
                'published_year' => 2019,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 135,
                'category_id' => 1,
                'title' => 'PENDIDIKAN KARAKTER: Konsepsi & Implementasi Secara Terpadu di Lingkungan Keluarga',
                'slug' => 'pendidikan-karakter',
                'author' => 'Syamsul Kurniawan',
                'publisher' => 'Ar-Ruzz Media',
                'published_year' => 2020,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 136,
                'category_id' => 1,
                'title' => 'PENDIDIKAN KRITIS : Kritik atas Praksis Neo-Liberalisasi dan Standardisasi Pendidikan',
                'slug' => 'pendidikan-kritis',
                'author' => 'Edi Subkhan, M. Pd.',
                'publisher' => 'Ar-Ruzz Media',
                'published_year' => 2020,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 137,
                'category_id' => 1,
                'title' => 'PENDIDIKAN POSMODERNISME: Telaah Kritis Pemikiran Tokoh Pendidikan',
                'slug' => 'pendidikan-posmodernisme',
                'author' => 'Mukhrizal Arif, Dkk.',
                'publisher' => 'Ar-Ruzz Media',
                'published_year' => 2020,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 138,
                'category_id' => 32,
                'title' => 'Pendidikan Rusak-Rusakan',
                'slug' => 'pendidikan-rusak-rusakan',
                'author' => 'Ki Darmaningtyas',
                'publisher' => 'Buku Bijak',
                'published_year' => 2022,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 139,
                'category_id' => 1,
                'title' => 'PENDIDIKAN UNTUK ORANG MISKIN',
                'slug' => 'pendidikan-untuk-orang-miskin',
                'author' => 'Mohammad Saroni',
                'publisher' => 'Ar-Ruzz Media',
                'published_year' => 2020,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 140,
                'category_id' => 1,
                'title' => 'PENELITIAN FENOMENOLOGI PENDIDIKAN: Teori dan Praktik',
                'slug' => 'penelitian-fenomenologi-pendidikan',
                'author' => 'Barnawi & Jajat Darojat',
                'publisher' => 'Ar-Ruzz Media',
                'published_year' => 2018,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 141,
                'category_id' => 43,
                'title' => 'Mengejar ekonomi, mengalahkan pandemi',
                'slug' => 'mengejar-ekonomi-mengalahkan-pandemi',
                'author' => 'Syamsul Arifin',
                'publisher' => 'Lembaga Kajian Profesi',
                'published_year' => 2022,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 142,
                'category_id' => 29,
                'title' => 'PERDAGANGAN MANUSIA BERKEDOK PENGIRIMAN TKI',
                'slug' => 'perdagangan-manusia-berkedok-pengiriman-tki',
                'author' => 'S. Edi Hardum',
                'publisher' => 'Ar-Ruzz Media',
                'published_year' => 2020,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 143,
                'category_id' => 5,
                'title' => 'Pertolongan "Dokter" Pertama di Rumah Anda',
                'slug' => 'pertolongan-dokter-pertama-di-rumah-anda',
                'author' => 'Yettik Wulandari',
                'publisher' => 'Trans Idea Publishing',
                'published_year' => 2020,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 144,
                'category_id' => 30,
                'title' => 'MENGENAL SARAF PADA MANUSIA',
                'slug' => 'mengenal-saraf-pada-manusia-2',
                'author' => 'Ria Setyo Mardani',
                'publisher' => 'Trans Idea Publishing',
                'published_year' => 2020,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 145,
                'category_id' => 15,
                'title' => 'Petunjuk Praktis Budidaya Sawi Pakcoy Cepat Panen',
                'slug' => 'petunjuk-praktis-budidaya-sawi-pakcoy',
                'author' => 'Eko Susilo',
                'publisher' => 'Litera Media Creativa',
                'published_year' => 2020,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 146,
                'category_id' => 29,
                'title' => 'Pidana Untuk Pemegang Saham Korporasi',
                'slug' => 'pidana-untuk-pemegang-saham-korporasi',
                'author' => 'DR. Ari Yusuf Amir, SH, MH',
                'publisher' => 'Ar-Ruzz Media',
                'published_year' => 2020,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 147,
                'category_id' => 12,
                'title' => 'Pocut Bareun: Pemimpin Perang Gerilya yang Pemberani dan Inspiratif',
                'slug' => 'pocut-bareun',
                'author' => 'Arslan Mukhtar',
                'publisher' => 'Edulitera',
                'published_year' => 2022,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 148,
                'category_id' => 12,
                'title' => 'PRABOWO SUBIANTO: Jalan Terjal Seorang Jenderal',
                'slug' => 'prabowo-subianto',
                'author' => 'Ade Ma\'ruf',
                'publisher' => 'Ar-Ruzz Media',
                'published_year' => 2020,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 149,
                'category_id' => 12,
                'title' => 'PRAMOEDYA ANANTA TOER: Biografi Singkat (1925-2006)',
                'slug' => 'pramoedya-ananta-toer',
                'author' => 'Muhammad Rifai',
                'publisher' => 'Garasi',
                'published_year' => 2020,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 150,
                'category_id' => 1,
                'title' => 'PROFESI KEGURUAN: Konsep & Strategi Mengembangkan Profesi & Karier Guru',
                'slug' => 'profesi-keguruan',
                'author' => 'Dr. Rulam Ahmadi, M.Pd.',
                'publisher' => 'Ar-Ruzz Media',
                'published_year' => 2018,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 151,
                'category_id' => 9,
                'title' => 'Prospek Agribisnis Budidaya Jeruk Nipis',
                'slug' => 'prospek-agribisnis-budidaya-jeruk-nipis',
                'author' => 'Aina Siwi',
                'publisher' => 'Lembaga Kajian Profesi',
                'published_year' => 2018,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 152,
                'category_id' => 9,
                'title' => 'Prospek Cerah Budidaya Bayam Merah',
                'slug' => 'prospek-cerah-budidaya-bayam-merah',
                'author' => 'Hans Warsoyo',
                'publisher' => 'Lembaga Kajian Profesi',
                'published_year' => 2018,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 153,
                'category_id' => 21,
                'title' => 'PSIKOLOGI KEPRIBADIAN DENGAN PERSPEKTIF BARU',
                'slug' => 'psikologi-kepribadian-dengan-perspektif-baru',
                'author' => 'Purwa Atmaja Prawira',
                'publisher' => 'Ar-Ruzz Media',
                'published_year' => 2020,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 154,
                'category_id' => 1,
                'title' => 'PSIKOLOGI PENDIDIKAN: Teori dan Aplikasi dalam Proses Pembelajaran',
                'slug' => 'psikologi-pendidikan',
                'author' => 'Muhamad Irham, Novan Ardy Wiyani',
                'publisher' => 'Ar-Ruzz Media',
                'published_year' => 2020,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 155,
                'category_id' => 39,
                'title' => 'Punya Barang Bekas? Daur Ulang Jadikan Uang',
                'slug' => 'punya-barang-bekas-daur-ulang-jadikan-uang',
                'author' => 'Prima Olimpiade Kristi dan Nurhastuti Putri Utami',
                'publisher' => 'Trans Idea Publishing',
                'published_year' => 2020,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 156,
                'category_id' => 1,
                'title' => 'QUANTIM PARENTING: Kiat Sukses Mengasuh Anak Secara Efektif dan Cerdas',
                'slug' => 'quantim-parenting',
                'author' => 'Mohammad Takdir Ilahi',
                'publisher' => 'Kata Hati',
                'published_year' => 2020,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 157,
                'category_id' => 12,
                'title' => 'R.A. KARTINI: Biografi Singkat 1879-1904',
                'slug' => 'ra-kartini',
                'author' => 'Imron Rosyadi',
                'publisher' => 'Garasi',
                'published_year' => 2020,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 158,
                'category_id' => 39,
                'title' => 'Ragam Kreasi Anyaman Rotan: Peluang Bisnis Menguntungkan',
                'slug' => 'ragam-kreasi-anyaman-rotan',
                'author' => 'Melanie Larasati',
                'publisher' => 'Trans Idea Publishing',
                'published_year' => 2018,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 159,
                'category_id' => 11,
                'title' => 'Ragam Kreasi Hantaran',
                'slug' => 'ragam-kreasi-hantaran',
                'author' => 'Istiana Sari',
                'publisher' => 'Litera Media Creativa',
                'published_year' => 2020,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 160,
                'category_id' => 3,
                'title' => 'RAGAM KUDAPAN SINGKONG',
                'slug' => 'ragam-kudapan-singkong',
                'author' => 'Ike P Sari',
                'publisher' => 'Kata Hati',
                'published_year' => 2019,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 161,
                'category_id' => 3,
                'title' => 'RAGAM MENU SARAPAN DARI NUSANTARA HINGGA DUNIA',
                'slug' => 'ragam-menu-sarapan',
                'author' => 'Ike P Sari',
                'publisher' => 'Kata Hati',
                'published_year' => 2018,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 162,
                'category_id' => 1,
                'title' => 'RAHASIA MENJADI GURU IDOLA',
                'slug' => 'rahasia-menjadi-guru-idola',
                'author' => 'Erwin Widianworo S.Pd.',
                'publisher' => 'Ar-Ruzz Media',
                'published_year' => 2020,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 163,
                'category_id' => 1,
                'title' => 'RAHASIA MENJADI PENDIDIK JEMPOLAN SEKALIGUS MOTIVATOR ULUNG DALAM HITUNGAN MENIT',
                'slug' => 'rahasia-menjadi-pendidik-jempolan',
                'author' => 'Ali Akbar Navis, Spd. CHt, Cl.',
                'publisher' => 'Ar-Ruzz Media',
                'published_year' => 2020,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 164,
                'category_id' => 2,
                'title' => 'Recharge Your Spirit',
                'slug' => 'recharge-your-spirit',
                'author' => 'Keen Achroni',
                'publisher' => 'Trans Idea Publishing',
                'published_year' => 2020,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
            [
                'id' => 165,
                'category_id' => 10,
                'title' => 'Resep Ampuh Pendongkrak Kesuburan',
                'slug' => 'resep-ampuh-pendongkrak-kesuburan',
                'author' => 'Nattaya Lakshita',
                'publisher' => 'Trans Idea Publishing',
                'published_year' => 2020,
                'description' => null,
                'stock' => 10,
                'cover_image' => null
            ],
        ]);
    }
}
